
---
- name: Create user automation on all managed hosts
  hosts: ansible[1-4]*
  become: true
  vars_files:
    - creds.yml
  tasks:
    - name: Creating the user 
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
        update_password: on_create
    
    - name: Copy the ssh_key to all servers
      ansible.posix.authorized_key:
        user: automation
        key: "{{ lookup('file', '/home/automation/plays/id_rsa.pub') }}"
        state: present

    - name: Allow automation user to elevate privileges without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: 'automation ALL=(ALL:ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'


