
---
- name: File Content
  hosts: all
  become: true
  tasks:
    - name: Use template to configure motd
      ansible.builtin.copy:
        content: "Welcome to HAProxy server"
        dest: /etc/motd
      when: "'proxy' in group_names"


    - name: Use template to configure motd
      ansible.builtin.copy:
        content: "Welcome to Aapche server"
        dest: /etc/motd
      when: "'webservers' in group_names"


    - name: Use template to configure motd
      ansible.builtin.copy:
        content: "Welcome to MySQL server"
        dest: /etc/motd
      when: "'database' in group_names"


    - name: Use template to configure motd
      ansible.builtin.copy:
        content: "Welcome to test server"
        dest: /etc/motd
      when: "'test' in group_names"
