
---
- name: Software Repositories
  hosts: database
  become: true
  tasks:
    - name: Add repository
      ansible.builtin.yum_repository:
        name: epel.repo
        description: "Internal YUM/DNF repo"
        baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        enabled: true
        gpgcheck: true

    - name: Import a key from a url
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
